# Generated by Django 3.2.20 on 2023-07-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='phone_number',
        ),
    ]
