# Generated by Django 3.2.20 on 2023-07-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_auto_20230715_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='materials_provide',
        ),
        migrations.AddField(
            model_name='form',
            name='materials_provide',
            field=models.ManyToManyField(to='bankapp.Material'),
        ),
    ]
